Real = int(input("enter the real number : "))
Complex = int(input("enter the complex number : "))
Complex_num = complex(Real,Complex)
# print(Real)
# print(Complex)
print(Complex_num)
print(type(Complex_num))
